Repository entando/entando-plugin-jpversioning, pull requests merged in 2020-11, with the labels that each got.

#9 ENG-1503 Changing behavior when version is not found, returning now a…
  src/main/java/org/entando/entando/plugins/jpversioning/services/content/ContentVersioningService.java
  src/main/java/org/entando/entando/plugins/jpversioning/web/content/ContentVersioningController.java
  src/test/java/org/entando/entando/jpversioning/web/content/ContentVersioningControllerIntegrationTest.java
  src/test/java/org/entando/entando/jpversioning/web/content/ContentVersioningControllerTest.java
Labels: approved, size/M

#10 ENG-1512: Added extra param "csp.header.extraConfig"
  src/test/config/conf/systemParams.properties
Labels: approved, size/XS

#11 ENG-1512: Update BOM and snapshot version
  pom.xml
  src/test/java/com/agiletec/plugins/jpversioning/aps/system/services/resource/MockResourceDataBean.java
Labels: approved, size/S
